import 'sort_descriptor.dart';

/// A composable, type-safe filter for model type [T].
///
/// Predicates are built from [QueryField] operators and combined with
/// `&` (AND), `|` (OR), and `!` (NOT). They compile down to a SQL
/// WHERE clause fragment when executed by [ModelContext].
///
/// Do not construct directly — use the generated `$ClassName` fields.
class Predicate<T> {
  /// The SQL fragment, e.g. `"destination = ?"`.
  final String sql;

  /// Positional arguments corresponding to `?` placeholders in [sql].
  final List<Object?> arguments;

  const Predicate(this.sql, this.arguments);

  /// AND — both predicates must be true.
  Predicate<T> operator &(Predicate<T> other) => Predicate<T>(
        '(${sql}) AND (${other.sql})',
        [...arguments, ...other.arguments],
      );

  /// OR — at least one predicate must be true.
  Predicate<T> operator |(Predicate<T> other) => Predicate<T>(
        '(${sql}) OR (${other.sql})',
        [...arguments, ...other.arguments],
      );

  /// NOT — inverts this predicate.
  Predicate<T> operator -() => Predicate<T>('NOT (${sql})', arguments);
}

/// A typed reference to a single column in a `@model` table.
///
/// Generated by dartdata_generator as a static field on `$ClassName`.
/// Use its methods to build [Predicate]s and [SortDescriptor]s.
class QueryField<V> {
  final String columnName;

  const QueryField(this.columnName);

  // -------------------------------------------------------------------------
  // Equality
  // -------------------------------------------------------------------------

  Predicate<dynamic> equals(V value) =>
      Predicate('$columnName = ?', [_encode(value)]);

  Predicate<dynamic> notEquals(V value) =>
      Predicate('$columnName != ?', [_encode(value)]);

  Predicate<dynamic> isNull() => Predicate('$columnName IS NULL', []);

  Predicate<dynamic> isNotNull() => Predicate('$columnName IS NOT NULL', []);

  // -------------------------------------------------------------------------
  // Comparison (for Comparable types)
  // -------------------------------------------------------------------------

  Predicate<dynamic> operator >(V value) =>
      Predicate('$columnName > ?', [_encode(value)]);

  Predicate<dynamic> operator >=(V value) =>
      Predicate('$columnName >= ?', [_encode(value)]);

  Predicate<dynamic> operator <(V value) =>
      Predicate('$columnName < ?', [_encode(value)]);

  Predicate<dynamic> operator <=(V value) =>
      Predicate('$columnName <= ?', [_encode(value)]);

  Predicate<dynamic> between(V low, V high) =>
      Predicate('$columnName BETWEEN ? AND ?', [_encode(low), _encode(high)]);

  // -------------------------------------------------------------------------
  // Collections
  // -------------------------------------------------------------------------

  Predicate<dynamic> isIn(List<V> values) {
    final placeholders = List.filled(values.length, '?').join(', ');
    return Predicate(
        '$columnName IN ($placeholders)', values.map(_encode).toList());
  }

  // -------------------------------------------------------------------------
  // String operations (only valid when V == String)
  // -------------------------------------------------------------------------

  Predicate<dynamic> contains(String substring) =>
      Predicate('$columnName LIKE ? ESCAPE "\\"', ['%${_escapeLike(substring)}%']);

  Predicate<dynamic> startsWith(String prefix) =>
      Predicate('$columnName LIKE ? ESCAPE "\\"', ['${_escapeLike(prefix)}%']);

  Predicate<dynamic> endsWith(String suffix) =>
      Predicate('$columnName LIKE ? ESCAPE "\\"', ['%${_escapeLike(suffix)}']);

  static String _escapeLike(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('%', '\\%').replaceAll('_', '\\_');

  // -------------------------------------------------------------------------
  // Sorting
  // -------------------------------------------------------------------------

  SortDescriptor<dynamic> ascending() =>
      SortDescriptor(columnName, ascending: true);

  SortDescriptor<dynamic> descending() =>
      SortDescriptor(columnName, ascending: false);

  // -------------------------------------------------------------------------
  // Internal encoding — converts Dart values to SQLite-compatible types
  // -------------------------------------------------------------------------

  Object? _encode(V value) {
    if (value is DateTime) return value.toUtc().millisecondsSinceEpoch;
    if (value is bool) return value ? 1 : 0;
    return value;
  }
}
